# Generated by Django 2.2 on 2020-11-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_login_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_data',
        ),
    ]
